/*********************************************************************
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE. 
* 
* std::map<std::string, int> uinputKeyMap                            *
* std::map<std::string, int> shortcutParserKeyMap                    *
*         	                                                         *
* Version: 1.0                                                       *
* Date:    09-02-2025                                                *
* Author:  Dan Machado                                               *
**********************************************************************/
#ifndef UINPUT_KEYMAP_H
#define UINPUT_KEYMAP_H
#include "key_index.h"

#include <map>

#include <linux/uinput.h>

//====================================================================

static const std::map<std::string, int> uinputKeyMap
{
	{"0",									KEY_0},
	{"1",									KEY_1},
	{"2",									KEY_2},
	{"3",									KEY_3},
	{"4",									KEY_4},
	{"5",									KEY_5},
	{"6",									KEY_6},
	{"7",									KEY_7},
	{"8",									KEY_8},
	{"9",									KEY_9},
	{"A",									KEY_A},
	{"AGAIN",							KEY_AGAIN},
	{"ALT", 								KEY_LEFTALT},
	{"ALTERNATE_ERASE",				KEY_UNKNOWN},
	{"ALT_LEFT",						KEY_LEFTALT},
	{"ALT_RIGHT",						KEY_RIGHTALT},
	{"APOSTROPHE",						KEY_APOSTROPHE},
	{"APPLICATION",					KEY_COMPOSE},
	{"ARROW_DOWN",						KEY_DOWN},
	{"ARROW_LEFT",						KEY_LEFT},
	{"ARROW_RIGHT",					KEY_RIGHT},
	{"ARROW_UP",						KEY_UP},
	{"B",									KEY_B},
	{"BACKSLASH",						KEY_BACKSLASH},
	{"BACKSLASH_EXT",					KEY_102ND},
	{"BACKSPACE",						KEY_BACKSPACE},
	{"BRACKET_LEFT",					KEY_LEFTBRACE},
	{"BRACKET_RIGHT",					KEY_RIGHTBRACE},
	{"C",									KEY_C},
	{"CANCEL",							KEY_UNKNOWN},
	{"CAPS_LOCK",						KEY_CAPSLOCK},
	{"CLEAR",							KEY_DELETE},
	{"CLEAR_AGAIN",					KEY_UNKNOWN},
	{"COMMA",							KEY_COMMA},
	{"CONTROL_LEFT",					KEY_LEFTCTRL},
	{"CONTROL_RIGHT",					KEY_RIGHTCTRL},
	{"COPY",								KEY_COPY},
	{"CRSEL_PROPS",					KEY_UNKNOWN},
	{"CTRL",								KEY_LEFTCTRL},
	{"CURRENCY_SUBUNIT",				KEY_UNKNOWN},
	{"CURRENCY_UNIT",					KEY_UNKNOWN},
	{"CUT",								KEY_CUT},
	{"D",									KEY_D},
	{"DECIMAL_SEPARATOR",			KEY_UNKNOWN},
	{"DELETE",							KEY_DELETE},
	{"E",									KEY_E},
	{"END",								KEY_END},
	{"ENTER",							KEY_ENTER},
	{"EQUAL",							KEY_EQUAL},
	{"ESC",								KEY_ESC},
	{"ESCAPE",							KEY_ESC},
	{"EUROPE_1",						KEY_BACKSLASH},
	{"EUROPE_2",						KEY_102ND},
	{"EXECUTE",							KEY_OPEN},
	{"EXSEL",							KEY_UNKNOWN},
	{"F",									KEY_F},
	{"F1",								KEY_F1},
	{"F10",								KEY_F10},
	{"F11",								KEY_F11},
	{"F12",								KEY_F12},
	{"F13",								KEY_F13},
	{"F14",								KEY_F14},
	{"F15",								KEY_F15},
	{"F16",								KEY_F16},
	{"F17",								KEY_F17},
	{"F18",								KEY_F18},
	{"F19",								KEY_F19},
	{"F2",								KEY_F2},
	{"F20",								KEY_F20},
	{"F21",								KEY_F21},
	{"F22",								KEY_F22},
	{"F23",								KEY_F23},
	{"F24",								KEY_F24},
	{"F3",								KEY_F3},
	{"F4",								KEY_F4},
	{"F5",								KEY_F5},
	{"F6",								KEY_F6},
	{"F7",								KEY_F7},
	{"F8",								KEY_F8},
	{"F9",								KEY_F9},
	{"FIND",								KEY_FIND},
	{"G",									KEY_G},
	{"GRAVE",							KEY_GRAVE},
	{"H",									KEY_H},
	{"HASH_EXT",						KEY_BACKSLASH},
	{"HELP",								KEY_HELP},
	{"HOME",								KEY_HOME},
	{"I",									KEY_I},
	{"INSERT",							KEY_INSERT},
	{"J",									KEY_J},
	{"K",									KEY_K},
	{"KANJI1",							KEY_RO},
	{"KANJI2",							KEY_KATAKANAHIRAGANA},
	{"KANJI3",							KEY_YEN},
	{"KANJI4",							KEY_HENKAN},
	{"KANJI5",							KEY_MUHENKAN},
	{"KANJI6",							KEY_KPJPCOMMA},
	{"KANJI7",							KEY_UNKNOWN},
	{"KANJI8",							KEY_UNKNOWN},
	{"KANJI9",							KEY_UNKNOWN},
	{"KEYPAD_0",						KEY_KP0},
	{"KEYPAD_00",						KEY_UNKNOWN},
	{"KEYPAD_000",						KEY_UNKNOWN},
	{"KEYPAD_1",						KEY_KP1},
	{"KEYPAD_2",						KEY_KP2},
	{"KEYPAD_3",						KEY_KP3},
	{"KEYPAD_4",						KEY_KP4},
	{"KEYPAD_5",						KEY_KP5},
	{"KEYPAD_6",						KEY_KP6},
	{"KEYPAD_7",						KEY_KP7},
	{"KEYPAD_8",						KEY_KP8},
	{"KEYPAD_9",						KEY_KP9},
	{"KEYPAD_A",						KEY_UNKNOWN},
	{"KEYPAD_ADD",						KEY_KPPLUS},
	{"KEYPAD_AMPERSAND",				KEY_UNKNOWN},
	{"KEYPAD_AT",						KEY_UNKNOWN},
	{"KEYPAD_B",						KEY_UNKNOWN},
	{"KEYPAD_BACKSPACE",				KEY_UNKNOWN},
	{"KEYPAD_BINARY",					KEY_UNKNOWN},
	{"KEYPAD_C",						KEY_UNKNOWN},
	{"KEYPAD_CARET",					KEY_DELETE},
	{"KEYPAD_CLEAR",					KEY_UNKNOWN},
	{"KEYPAD_CLEAR_ENTRY",			KEY_UNKNOWN},
	{"KEYPAD_COLON",					KEY_KPCOMMA},
	{"KEYPAD_COMMA",					KEY_UNKNOWN},
	{"KEYPAD_D",						KEY_KPDOT},
	{"KEYPAD_DECIMAL",				KEY_KPSLASH},
	{"KEYPAD_DECIMAL_2",				KEY_UNKNOWN},
	{"KEYPAD_DIVIDE",					KEY_UNKNOWN},
	{"KEYPAD_DOUBLE_AMPERSAND",	KEY_UNKNOWN},
	{"KEYPAD_DOUBLE_VERTICAL_BAR",KEY_KPENTER},
	{"KEYPAD_E",						KEY_KPEQUAL},
	{"KEYPAD_ENTER",					KEY_UNKNOWN},
	{"KEYPAD_EQUAL",					KEY_UNKNOWN},
	{"KEYPAD_EQUAL_SIGN",			KEY_UNKNOWN},
	{"KEYPAD_EXCLAMATION",			KEY_UNKNOWN},
	{"KEYPAD_F",						KEY_UNKNOWN},
	{"KEYPAD_GREATER_THAN",			KEY_UNKNOWN},
	{"KEYPAD_HASH",					KEY_KPLEFTPAREN},
	{"KEYPAD_HEXADECIMAL",			KEY_UNKNOWN},
	{"KEYPAD_LEFT_BRACE",			KEY_UNKNOWN},
	{"KEYPAD_LEFT_PARENTHESIS",	KEY_UNKNOWN},
	{"KEYPAD_LESS_THAN",				KEY_UNKNOWN},
	{"KEYPAD_MEMORY_ADD",			KEY_UNKNOWN},
	{"KEYPAD_MEMORY_CLEAR",			KEY_UNKNOWN},
	{"KEYPAD_MEMORY_DIVIDE",		KEY_UNKNOWN},
	{"KEYPAD_MEMORY_MULTIPLY",		KEY_UNKNOWN},
	{"KEYPAD_MEMORY_RECALL",		KEY_KPASTERISK},
	{"KEYPAD_MEMORY_STORE",			KEY_UNKNOWN},
	{"KEYPAD_MEMORY_SUBTRACT",		KEY_UNKNOWN},
	{"KEYPAD_MULTIPLY",				KEY_UNKNOWN},
	{"KEYPAD_OCTAL",					KEY_KPRIGHTPAREN},
	{"KEYPAD_PERCENT",				KEY_UNKNOWN},
	{"KEYPAD_PLUS_MINUS",			KEY_KPMINUS},
	{"KEYPAD_RIGHT_BRACE",			KEY_UNKNOWN},
	{"KEYPAD_RIGHT_PARENTHESIS",	KEY_UNKNOWN},// */
	//"KEYPAD_SPACE",							},
	//"KEYPAD_SUBTRACT",							},
	//"KEYPAD_TAB",							},
	//"KEYPAD_VERTICAL_BAR",							},
	//"KEYPAD_XOR",						},
	{"L",									KEY_L},
	{"LANG1",							KEY_HANGEUL},
	{"LANG2",							KEY_HANJA},
	{"LANG3",							KEY_KATAKANA},
	{"LANG4",							KEY_HIRAGANA},
	{"LANG5",							KEY_ZENKAKUHANKAKU},
	{"LANG6",							KEY_UNKNOWN},
	{"LANG7",							KEY_UNKNOWN},
	{"LANG8",							KEY_UNKNOWN},
	{"LANG9",							KEY_UNKNOWN},
	{"LOCKING_CAPS_LOCK",			KEY_UNKNOWN},
	{"LOCKING_NUM_LOCK",				KEY_UNKNOWN},
	{"LOCKING_SCROLL_LOCK",			KEY_UNKNOWN},
	{"M",									KEY_M},
	{"MENU",								KEY_PROPS},
	{"META_LEFT",						KEY_LEFTMETA},
	{"META_RIGHT",						KEY_RIGHTMETA},
	{"MINUS",							KEY_MINUS},
	{"MUTE",								KEY_MUTE},
	{"N",									KEY_N},
	//"NONE",								},
	{"NUM_LOCK",						KEY_NUMLOCK},
	{"O",									KEY_O},
	{"OPER",								KEY_UNKNOWN},
	{"OUT",								KEY_UNKNOWN},
	{"P",									KEY_P},
	{"PAGE_DOWN",						KEY_PAGEDOWN},
	{"PAGE_UP",							KEY_PAGEUP},
	{"PASTE",							KEY_PASTE},
	{"PAUSE",							KEY_PAUSE},
	{"PERIOD",							KEY_DOT},
	{"POWER",							KEY_POWER},
	{"PRINTSCREEN",					KEY_SYSRQ},
	{"PRINT_SCREEN",					KEY_SYSRQ},
	{"PRIOR",							KEY_UNKNOWN},
	{"Q",									KEY_Q},
	{"R",									KEY_R},
	{"RETURN",							KEY_UNKNOWN},
	{"S",									KEY_S},
	{"SCROLL_LOCK",					KEY_SCROLLLOCK},
	{"SELECT",							KEY_FRONT},
	{"SEMICOLON",						KEY_SEMICOLON},
	{"SEPARATOR",						KEY_UNKNOWN},
	{"SHIFT",							KEY_LEFTSHIFT},
	{"SHIFT_LEFT",						KEY_LEFTSHIFT},
	{"SHIFT_RIGHT",					KEY_RIGHTSHIFT},
	{"SLASH",							KEY_SLASH},
	{"SPACE",							KEY_SPACE},
	{"STOP",								KEY_STOP},
	{"SYSREQ_ATTENTION",				KEY_UNKNOWN},
	{"T",									KEY_T},
	{"TAB",								KEY_TAB},
	{"THOUSANDS_SEPARATOR",			KEY_UNKNOWN},
	{"U",									KEY_U},
	{"UNDO",								KEY_UNDO},
	{"V",									KEY_V},
	{"VOLUME_DOWN",					KEY_VOLUMEDOWN},
	{"VOLUME_UP",						KEY_VOLUMEUP},
	{"W",									KEY_W},
	{"X",									KEY_X},
	{"Y",									KEY_Y},
	{"Z",									KEY_Z}
};

//====================================================================

#endif											
